# Generated by Django 2.2.13 on 2021-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField()),
                ('rank', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('time', models.DateField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('actor', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('time', models.DateField()),
            ],
        ),
    ]
