# Generated by Django 2.2.13 on 2021-01-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210117_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
