# Generated by Django 2.2.13 on 2021-01-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210117_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='film_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='filmname',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
